apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3ta-vm
  annotations:
    # Runs in parallel with 3ta-vks
    argocd.argoproj.io/sync-wave: "-1" 
spec:
  project: default
  source:
    repoURL: 'https://github.com/KBrookfield/3ta-demo'
    targetRevision: main
    path: 3ta/apps/3ta-vm
    directory:
      recurse: true
  destination:
    server: 'https://32.32.0.2:443'
    namespace: dev-w6vw5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: mysql-vm-bootstrap-secret
      namespace: dev-w6vw5
      jsonPointers:
        - /metadata/annotations  
      kind: Secret
      name: mysql-vm-bootstrap-secret
      namespace: dev-w6vw5
      jqPathExpressions:
        - '.data."user-data"'
    - group: vmoperator.vmware.com
      kind: VirtualMachine
      name: mysql-vm
      namespace: dev-w6vw5
      jsonPointers:
        - /spec/imageName
    - group: vmoperator.vmware.com
      kind: VirtualMachineService
      jsonPointers:
        - /metadata/annotations
        - /spec/selector